Fix behaviour for brep files without metadata
When attempting to process a brep file which did not have an
associated metadata file, there was an obscure error:

  RuntimeError: [json.exception.type_error.302] type must be string, but is null

With this fix there is now a warning that no metadata has been
provided, and then PPP continues.